version: '3.7'
services:

  redis:
    image: redis:latest

  web:
    container_name: web
    image: nginx:alpine
    networks:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/conf/default.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php
    build:
      context: ./docker
    ports:
      - "8000:8000"
    networks:
      - frontend
      - backend
    depends_on:
      - mariadb
    environment:
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb:latest
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/config:/etc/mysql/conf.d
      - ./mariadb/backup-volume:/backup
      - ./mariadb/datadir:/var/lib/mysql:Z
    env_file:
      - ./.env
    environment:
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      
networks:
  frontend:
  backend:      

      
